# Field mapping for trinity nomenclature
# This file contains the mapping between field names and their display labels

field_mapping = {
    "meta_descriptionen": "Language EN",
    "meta_fhir_mapping": "FHIR Mapping",
    "meta_description_bg_agent": "Описание (bg_agent)",
    "meta_role": "Role in Healthcare",
    "meta_nhif_code": "NHIF Code",
    "meta_nhif_name": "NHIF Name",
    "meta_clinical_speciality": "Clinical Speciality",
    "meta_nhif_document": "NHIF Document",
    "meta_description": "Description",
    "meta_inn_code": "INN код",
    "meta_inn": "INN код",
    "meta_atc": "ATC",
    "meta_form": "Форма",
    "meta_form_bg": "Форма BG",
    "meta_form_id": "Форма",
    "meta_package": "Пакет",
    "meta_permit_owner": "Собственик на разрешение",
    "meta_permit_number": "Номер на разрешение",
    "meta_is_narcotic": "Е наркотик",
    "meta_units": "Мерни единици",
    "meta_quantity": "Количество",
    "meta_full_title": "Пълно заглавие",
    "meta_updated_on": "Обновено на",
    "meta_status": "Статус",
    "meta_reportable": "Reportable",
    "meta_rare": "Rare",
    "meta_cancer": "Cancer",
    "meta_diabetes": "Diabetes",
    "meta_mental": "Mental",
    "meta_contagious": "Contagious (CL148)",
    "meta_display_value_bg": "Display Value BG",
    "meta_display_value_en": "Display Value EN",
    "meta_note": "Note",
    "meta_usage_instructions": "Usage Instructions",
    "meta_organization_bg": "Organization BG",
    "meta_organization_en": "Organization EN",
    "meta_latin": "Latin",
    "meta_way_of_prescribing_code": "Код на начина на предписване",
    "meta_divisible": "Делимо",
    "meta_narcotic": "Наркотик",
    "meta_medical_supply_list_type": "Тип списък медицински материали",
    "meta_flag_to_stop": "Флаг за спиране",
    "meta_prescription_type": "Тип рецепта",
    "meta_target_disease": "Целева болест",
    "meta_completely_paid": "Напълно платено",
    "meta_cl009": "CL009",
    "meta_mkbage": "МКБ възраст",
    "meta_target_disease_all": "Всички целеви болести",
    "meta_cl022_mapping": "CL022 Mapping",
    "meta_loinc": "LOINC***",
    "meta_cl028_mapping": "CL028 Mapping**",
    "meta_cl032_mapping": "CL032 Mapping**",
    "meta_ucum": "UCUM*",
    "meta_old_key": "Old Key",
    "meta_achi_chapter": "ACHI Chapter",
    "meta_achi_block": "ACHI Block",
    "meta_achi_code": "ACHI Code",
    "meta_nhif_package": "NHIF Package",
    "meta_cl006": "CL006",
    "meta_cl048": "CL048",
    "meta_fhir": "FHIR",
    "meta_type": "Type",
    "meta_test_type": "Тип тест",
    "meta_manifacturer": "Производител",
    "meta_country": "Country",
    "meta_website": "Website",
    "meta_dgc_approved": "DGC Approved",
    "meta_bg_approved": "BG Approved",
    "meta_medicament_details": "Medicament Details",
    "meta_vaccine_group": "Vaccine Group",
    "meta_dose_quantity_ml": "Dose Quantity (ml)",
    "meta_number_of_doses": "Number of Doses",
    "meta_days_to_next_dose": "Days to Next Dose",
    "meta_permit_owner_id": "Permit Owner ID",
    "meta_permit_owner_name": "Permit Owner Name",
    "meta_mh_code": "MH code",
    "meta_dose_number": "Dose Number",
    "meta_cl082_mapping": "CL082 Mapping",
    "meta_min_age": "Min age",
    "meta_max_age": "Max age**",
    "meta_rules": "Rules",
    "meta_vaccine_additional_info": "Vaccine additional info",
    "meta_cl037_mapping_2023": "CL037 Mapping (2023)",
    "meta_cl037_mapping_2024": "CL037 Mapping (2024)",
    "meta_display_transfered_data_bg": "Display transfered data BG",
    "meta_display_transfered_data_en": "Display transfered data EN",
    "meta_program_group": "Program Group",
    "meta_cl050_mapping": "CL50 Mapping",
    "meta_cl142_mapping": "CL142 Mapping",
    "meta_cl012_mapping": "CL012 Mapping",
    "meta_cl138_mapping": "CL138 Mapping",
    "meta_requires_text_conclusion": "Requires text conclusion",
    "meta_snomed": "SNOMED",
    "meta_offset_allowed": "Offset Allowed",
    "meta_instructions": "Instructions",
    "meta_tooth_group": "Tooth Group",
    "meta_tooth_type": "Tooth Type",
    "meta_nhif_text": "NHIF Text",
    "meta_incompatible_other_codes": "Incompatible other codes from CL107",
    "meta_required_other_codes": "Required other codes from CL107",
    "meta_cl112_mapping": "CL112 Mapping",
    "meta_cl011_mapping": "CL011 Mapping",
    "meta_source": "Source",
    "meta_applicable": "Applicable",
    "meta_nhif_mapping": "NHIF Mapping",
    "meta_notes": "Notes",
    "meta_orpha_diseases_label_bg": "Orpha diseases label BG",
    "meta_orpha_diseases_label_en": "Orpha diseases label EN",
    "meta_cl120_mapping": "CL120 Mapping",
    "meta_main": "Main",
    "meta_additional": "Additional",
    "meta_min_patient_age": "Min Patient Age",
    "meta_max_patient_age": "Max Patient Age",
    "meta_cl069_mapping": "CL069 Mapping",
    "meta_risk_group_definition": "Risk Group definition",
    "meta_cl126": "CL126",
    "meta_cl011": "CL011",
    "meta_data_from": "Data from",
    "meta_type_short": "Type short",
    "meta_cl047_mapping": "CL047 Mapping",
    "meta_cl136_mapping": "CL136 Mapping",
    "meta_event_trigger": "Event Trigger",
    "meta_common_index": "Common index",
    "meta_min_interval_from_common_index": "Min interval from common index",
    "meta_max_interval_from_common_index": "Max interval from common index",
    "meta_age": "Age",
    "meta_recurring": "Recurring",
    "meta_repeat_every_x_years": "Repeat Every x Years",
    "meta_gender": "Gender",
    "meta_cl133": "CL133",
    "meta_multiple_choice": "Multiple Choice",
    "meta_cl028": "CL028",
    "meta_answer_nomenclature": "Answer Nomenclature",
    "meta_ask_once": "Ask once",
    "meta_cl022": "CL022",
    "meta_min_interval": "Min interval",
    "meta_start_date": "Start date",
    "meta_end_date": "End date",
    "meta_cl021": "CL021",
    "meta_cl047": "CL047"
}
